import { Inter } from "next/font/google";
import Header from "./components/Header/Header";
import Container from "./components/container";
import "./globals.css";
import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Container>
          {children}
        </Container>
        <Footer />
        </body>
    </html>
  );
}
